# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sshauth.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diag_sshauth(object):
    def setupUi(self, diag_sshauth):
        diag_sshauth.setObjectName("diag_sshauth")
        diag_sshauth.setWindowModality(QtCore.Qt.ApplicationModal)
        diag_sshauth.resize(275, 170)
        self.verticalLayout = QtWidgets.QVBoxLayout(diag_sshauth)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wid_password = QtWidgets.QWidget(diag_sshauth)
        self.wid_password.setObjectName("wid_password")
        self.formLayout = QtWidgets.QFormLayout(self.wid_password)
        self.formLayout.setObjectName("formLayout")
        self.lbl_username = QtWidgets.QLabel(self.wid_password)
        self.lbl_username.setObjectName("lbl_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_username)
        self.lbl_password = QtWidgets.QLabel(self.wid_password)
        self.lbl_password.setObjectName("lbl_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_password)
        self.txt_password = QtWidgets.QLineEdit(self.wid_password)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_password)
        self.txt_username = QtWidgets.QLineEdit(self.wid_password)
        self.txt_username.setObjectName("txt_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_username)
        self.verticalLayout.addWidget(self.wid_password)
        self.wid_keys = QtWidgets.QWidget(diag_sshauth)
        self.wid_keys.setObjectName("wid_keys")
        self.verticalLayout.addWidget(self.wid_keys)
        self.buttonBox = QtWidgets.QDialogButtonBox(diag_sshauth)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(diag_sshauth)
        self.buttonBox.accepted.connect(diag_sshauth.accept) # type: ignore
        self.buttonBox.rejected.connect(diag_sshauth.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(diag_sshauth)

    def retranslateUi(self, diag_sshauth):
        _translate = QtCore.QCoreApplication.translate
        diag_sshauth.setWindowTitle(_translate("diag_sshauth", "SSH authentication"))
        self.lbl_username.setText(_translate("diag_sshauth", "SSH username:"))
        self.lbl_password.setText(_translate("diag_sshauth", "SSH password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    diag_sshauth = QtWidgets.QDialog()
    ui = Ui_diag_sshauth()
    ui.setupUi(diag_sshauth)
    diag_sshauth.show()
    sys.exit(app.exec_())
