#!/bin/sh
# This script will create the entry point 'revpicommander', which is defined
# in the setup.py script. If you want to install this python module as an
# application and not in the python standard library directory, you will need
# to use this script for /usr/bin.

exec python3 /usr/share/revpicommander/revpicommander "$@"
