name: binary_creation
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: generate exe
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: "RevPi Commander.spec"
        path: .
