# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'revpiplclist.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diag_connections(object):
    def setupUi(self, diag_connections):
        diag_connections.setObjectName("diag_connections")
        diag_connections.resize(520, 508)
        self.gridLayout = QtWidgets.QGridLayout(diag_connections)
        self.gridLayout.setObjectName("gridLayout")
        self.tre_connections = QtWidgets.QTreeWidget(diag_connections)
        self.tre_connections.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tre_connections.setObjectName("tre_connections")
        self.gridLayout.addWidget(self.tre_connections, 0, 0, 1, 1)
        self.vl_edit = QtWidgets.QVBoxLayout()
        self.vl_edit.setObjectName("vl_edit")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_edit.addItem(spacerItem)
        self.btn_up = QtWidgets.QPushButton(diag_connections)
        self.btn_up.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/action/ico/arrow-up.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon)
        self.btn_up.setObjectName("btn_up")
        self.vl_edit.addWidget(self.btn_up)
        self.btn_down = QtWidgets.QPushButton(diag_connections)
        self.btn_down.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/action/ico/arrow-down.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon1)
        self.btn_down.setObjectName("btn_down")
        self.vl_edit.addWidget(self.btn_down)
        self.btn_delete = QtWidgets.QPushButton(diag_connections)
        self.btn_delete.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/action/ico/edit-delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon2)
        self.btn_delete.setObjectName("btn_delete")
        self.vl_edit.addWidget(self.btn_delete)
        self.btn_add = QtWidgets.QPushButton(diag_connections)
        self.btn_add.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/action/ico/edit-add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon3)
        self.btn_add.setObjectName("btn_add")
        self.vl_edit.addWidget(self.btn_add)
        self.gridLayout.addLayout(self.vl_edit, 0, 1, 1, 1)
        self.gb_properties = QtWidgets.QGroupBox(diag_connections)
        self.gb_properties.setObjectName("gb_properties")
        self.formLayout = QtWidgets.QFormLayout(self.gb_properties)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QtWidgets.QLabel(self.gb_properties)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_name)
        self.lbl_folder = QtWidgets.QLabel(self.gb_properties)
        self.lbl_folder.setObjectName("lbl_folder")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_folder)
        self.lbl_address = QtWidgets.QLabel(self.gb_properties)
        self.lbl_address.setObjectName("lbl_address")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_address)
        self.lbl_port = QtWidgets.QLabel(self.gb_properties)
        self.lbl_port.setObjectName("lbl_port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_port)
        self.txt_name = QtWidgets.QLineEdit(self.gb_properties)
        self.txt_name.setObjectName("txt_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_name)
        self.txt_address = QtWidgets.QLineEdit(self.gb_properties)
        self.txt_address.setObjectName("txt_address")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_address)
        self.sbx_port = QtWidgets.QSpinBox(self.gb_properties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbx_port.sizePolicy().hasHeightForWidth())
        self.sbx_port.setSizePolicy(sizePolicy)
        self.sbx_port.setMinimum(1)
        self.sbx_port.setMaximum(65535)
        self.sbx_port.setProperty("value", 55123)
        self.sbx_port.setObjectName("sbx_port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sbx_port)
        self.cbb_folder = QtWidgets.QComboBox(self.gb_properties)
        self.cbb_folder.setEditable(True)
        self.cbb_folder.setObjectName("cbb_folder")
        self.cbb_folder.addItem("")
        self.cbb_folder.setItemText(0, "")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cbb_folder)
        self.lbl_timeout = QtWidgets.QLabel(self.gb_properties)
        self.lbl_timeout.setObjectName("lbl_timeout")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_timeout)
        self.sbx_timeout = QtWidgets.QSpinBox(self.gb_properties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbx_timeout.sizePolicy().hasHeightForWidth())
        self.sbx_timeout.setSizePolicy(sizePolicy)
        self.sbx_timeout.setMinimum(5)
        self.sbx_timeout.setMaximum(30)
        self.sbx_timeout.setObjectName("sbx_timeout")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbx_timeout)
        self.gridLayout.addWidget(self.gb_properties, 1, 0, 1, 2)
        self.btn_box = QtWidgets.QDialogButtonBox(diag_connections)
        self.btn_box.setOrientation(QtCore.Qt.Horizontal)
        self.btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Save)
        self.btn_box.setObjectName("btn_box")
        self.gridLayout.addWidget(self.btn_box, 2, 0, 1, 2)

        self.retranslateUi(diag_connections)
        self.btn_box.accepted.connect(diag_connections.accept)
        self.btn_box.rejected.connect(diag_connections.reject)
        QtCore.QMetaObject.connectSlotsByName(diag_connections)

    def retranslateUi(self, diag_connections):
        _translate = QtCore.QCoreApplication.translate
        diag_connections.setWindowTitle(_translate("diag_connections", "Revolution Pi connections"))
        self.tre_connections.headerItem().setText(0, _translate("diag_connections", "Connection name"))
        self.tre_connections.headerItem().setText(1, _translate("diag_connections", "Address"))
        self.gb_properties.setTitle(_translate("diag_connections", "Connection properties"))
        self.lbl_name.setText(_translate("diag_connections", "Display name:"))
        self.lbl_folder.setText(_translate("diag_connections", "Sub folder:"))
        self.lbl_address.setText(_translate("diag_connections", "Address (DNS/IP):"))
        self.lbl_port.setText(_translate("diag_connections", "Port (Default {0}):"))
        self.lbl_timeout.setText(_translate("diag_connections", "Connection timeout:"))
        self.sbx_timeout.setSuffix(_translate("diag_connections", " sec."))
from . import ressources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    diag_connections = QtWidgets.QDialog()
    ui = Ui_diag_connections()
    ui.setupUi(diag_connections)
    diag_connections.show()
    sys.exit(app.exec_())
